development:
  # adapter: sqlite3
  # database: db/sfi_development.sqlite3
  # pool: 5
  # timeout: 5000
  adapter: mysql2
  encoding: utf8
  database: spree_production
  username: SFI
  password: welovebubbles
  host: localhost